import { TelegramMessage } from "../types";

export const TELEGRAM_MESSAGES: TelegramMessage[] = [
  {
    id: 1,
    author: "TradeVerse Admin",
    role: "MOD",
    avatar: "T",
    bg: "bg-sky-600",
    text: "Chào mừng mọi người gia nhập kênh thảo luận TradeVerse Telegram! 🚀",
    time: "14:20",
  },
  {
    id: 2,
    author: "Tuấn Quant",
    role: "VIP",
    avatar: "T",
    bg: "bg-emerald-600",
    text: "Bài viết chia sẻ tư duy Backtest Python trên Kho Bài Viết hay quá ad ơi!",
    time: "14:21",
  },
  {
    id: 3,
    author: "Hoàng Trader",
    role: "Member",
    avatar: "H",
    bg: "bg-amber-600",
    text: "Ad ơi cho mình hỏi kịch bản nhận định cặp BTC phiên Mỹ hôm nay với?",
    time: "14:22",
  },
  {
    id: 4,
    author: "TradeVerse Admin",
    role: "MOD",
    avatar: "T",
    bg: "bg-sky-600",
    text: "Báo cáo Market Bias & kịch bản sóng 24/7 vừa cập nhật nhé cả nhà 📊",
    time: "14:23",
  },
  {
    id: 5,
    author: "Minh Châu",
    role: "VIP",
    avatar: "M",
    bg: "bg-purple-600",
    text: "Vừa TP +120 pips theo kịch bản nhận định sáng nay, uy tín quá 🔥",
    time: "14:24",
  },
  {
    id: 6,
    author: "Phương Nam",
    role: "Member",
    avatar: "P",
    bg: "bg-indigo-600",
    text: "Cộng đồng trao đổi xôm quá, cảm ơn bộ tài liệu 100+ bài viết miễn phí!",
    time: "14:25",
  },
  {
    id: 7,
    author: "Lê Khôi",
    role: "VIP",
    avatar: "K",
    bg: "bg-teal-600",
    text: "Cho mình hỏi link đăng ký gói TradingView Pro chiết khấu ad ơi?",
    time: "14:26",
  },
  {
    id: 8,
    author: "Đức Anh",
    role: "Member",
    avatar: "Đ",
    bg: "bg-rose-600",
    text: "Bot PineScript thông báo tín hiệu qua Telegram hoạt động mượt lắm!",
    time: "14:27",
  },
];
